import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private currentLanguage = new BehaviorSubject<string>(this.getInitialLanguage());
  public currentLanguage$ = this.currentLanguage.asObservable();

  private translations: Translations = {
    EN: {
      // Auth/Login
      'login.title': 'Login to NammaSociety',
      'login.username_password': 'Username & Password',
      'login.mobile_otp': 'Mobile & OTP',
      'login.username': 'Username',
      'login.password': 'Password',
      'login.captcha': 'Captcha',
      'login.login_button': 'Login',
      'login.register': "Don't have an account? Register",
      'login.forgot_password': 'Forgot Password?',
      'login.mobile_number': 'Mobile Number',
      'login.otp': 'OTP',
      'login.send_otp': 'Send OTP',
      'login.verify_otp': 'Verify OTP',
      'login.error': 'Login failed',
      'login.success': 'Login successful',
      
      // Register
      'register.title': 'Register to NammaSociety',
      'register.full_name': 'Full Name',
      'register.email': 'Email',
      'register.mobile': 'Mobile Number',
      'register.password': 'Password',
      'register.confirm_password': 'Confirm Password',
      'register.register_button': 'Register',
      'register.already_member': 'Already a member? Login',
      
      // Dashboard
      'dashboard.marketplace': 'Marketplace',
      'dashboard.guest_approvals': 'Guest Approvals',
      'dashboard.profile': 'Profile',
      'dashboard.logout': 'Logout',
      'dashboard.welcome': 'Welcome',
      'dashboard.search': 'Search',
      'dashboard.cart': 'Cart',
      'dashboard.orders': 'Orders',
      
      // Common
      'common.language': 'Language',
      'common.save': 'Save',
      'common.cancel': 'Cancel',
      'common.delete': 'Delete',
      'common.edit': 'Edit',
      'common.loading': 'Loading...',
      'common.error': 'Error',
      'common.success': 'Success',
    },
    HI: {
      'login.title': 'NammaSociety में लॉगिन करें',
      'login.username_password': 'यूजरनेम और पासवर्ड',
      'login.mobile_otp': 'मोबाइल और OTP',
      'login.username': 'यूजरनेम',
      'login.password': 'पासवर्ड',
      'login.captcha': 'कैप्चा',
      'login.login_button': 'लॉगिन',
      'login.register': 'खाता नहीं है? पंजीकरण करें',
      'login.forgot_password': 'पासवर्ड भूल गए?',
      'login.mobile_number': 'मोबाइल नंबर',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP भेजें',
      'login.verify_otp': 'OTP सत्यापित करें',
      'login.error': 'लॉगिन विफल',
      'login.success': 'लॉगिन सफल',
      
      'register.title': 'NammaSociety में पंजीकरण करें',
      'register.full_name': 'पूरा नाम',
      'register.email': 'ईमेल',
      'register.mobile': 'मोबाइल नंबर',
      'register.password': 'पासवर्ड',
      'register.confirm_password': 'पासवर्ड की पुष्टि करें',
      'register.register_button': 'पंजीकरण करें',
      'register.already_member': 'पहले से सदस्य? लॉगिन करें',
      
      'dashboard.marketplace': 'बाजार',
      'dashboard.guest_approvals': 'मेहमान अनुमोदन',
      'dashboard.profile': 'प्रोफ़ाइल',
      'dashboard.logout': 'लॉगआउट',
      'dashboard.welcome': 'स्वागत है',
      'dashboard.search': 'खोज',
      'dashboard.cart': 'कार्ट',
      'dashboard.orders': 'ऑर्डर',
      
      'common.language': 'भाषा',
      'common.save': 'सहेजें',
      'common.cancel': 'रद्द करें',
      'common.delete': 'हटाएं',
      'common.edit': 'संपादित करें',
      'common.loading': 'लोड हो रहा है...',
      'common.error': 'त्रुटि',
      'common.success': 'सफल',
    },
    TA: {
      'login.title': 'NammaSociety இல் உள்நுழையவும்',
      'login.username_password': 'பயனர்பெயர் மற்றும் கடவுச்சொல்',
      'login.mobile_otp': 'மொபைல் மற்றும் OTP',
      'login.username': 'பயனர்பெயர்',
      'login.password': 'கடவுச்சொல்',
      'login.captcha': 'கேப்চா',
      'login.login_button': 'உள்நுழைக',
      'login.register': 'கணக்கு இல்லையா? பதிவு செய்க',
      'login.forgot_password': 'கடவுச்சொல் மறந்துவிட்டீர்களா?',
      'login.mobile_number': 'மொபைல் எண்',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP அனுப்பவும்',
      'login.verify_otp': 'OTP சரிபார்க்கவும்',
      'login.error': 'உள்நுழைவு தோல்வி',
      'login.success': 'உள்நுழைவு வெற்றிகரமாக',
      
      'register.title': 'NammaSociety இல் பதிவு செய்க',
      'register.full_name': 'முழு பெயர்',
      'register.email': 'மின்னஞ்சல்',
      'register.mobile': 'மொபைல் எண்',
      'register.password': 'கடவுச்சொல்',
      'register.confirm_password': 'கடவுச்சொல்ஐ உறுதிசெய்க',
      'register.register_button': 'பதிவு செய்க',
      'register.already_member': 'ஏற்கனவே உறுப்பினரா? உள்நுழைக',
      
      'dashboard.marketplace': 'சந்தை',
      'dashboard.guest_approvals': 'விருந்தினர் ஒப்புதல்கள்',
      'dashboard.profile': 'சுயவிவரம்',
      'dashboard.logout': 'வெளியேறு',
      'dashboard.welcome': 'வரவேற்கிறோம்',
      'dashboard.search': 'தேடு',
      'dashboard.cart': 'கட்டுப்பு',
      'dashboard.orders': 'ஆர்டர்கள்',
      
      'common.language': 'மொழி',
      'common.save': 'சேமிக்கவும்',
      'common.cancel': 'ரத்து செய்க',
      'common.delete': 'நீக்கு',
      'common.edit': 'திருத்து',
      'common.loading': 'சுமைப்பு நடைபெறுகிறது...',
      'common.error': 'பிழை',
      'common.success': 'வெற்றி',
    },
    TE: {
      'login.title': 'NammaSocietyకి లాగిన్ చేయండి',
      'login.username_password': 'వినియోగదారు పేరు మరియు పాస్‌వర్డ్',
      'login.mobile_otp': 'మొబైల్ మరియు OTP',
      'login.username': 'వినియోగదారు పేరు',
      'login.password': 'పాస్‌వర్డ్',
      'login.captcha': 'కాప్చా',
      'login.login_button': 'లాగిన్',
      'login.register': 'ఖాతా లేనా? నమోదు చేయండి',
      'login.forgot_password': 'పాస్‌వర్డ్ మర్చిపోయారా?',
      'login.mobile_number': 'మొబైల్ నంబర్',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP పంపండి',
      'login.verify_otp': 'OTPని ధృవీకరించండి',
      'login.error': 'లాగిన్ విఫలమైంది',
      'login.success': 'లాగిన్ విజయవంతమైంది',
      
      'register.title': 'NammaSocietyకి నమోదు చేయండి',
      'register.full_name': 'పూర్తి పేరు',
      'register.email': 'ఇమెయిల్',
      'register.mobile': 'మొబైల్ నంబర్',
      'register.password': 'పాస్‌వర్డ్',
      'register.confirm_password': 'పాస్‌వర్డ్‌ను నిర్ధారించండి',
      'register.register_button': 'నమోదు చేయండి',
      'register.already_member': 'ఇప్పటికే సభ్యులు? లాగిన్ చేయండి',
      
      'dashboard.marketplace': 'మార్కెట్‌ప్లేస్',
      'dashboard.guest_approvals': 'అతిథి ఆమోదనలు',
      'dashboard.profile': 'ప్రొఫైల్',
      'dashboard.logout': 'లాగ్ అవుట్',
      'dashboard.welcome': 'స్వాగతం',
      'dashboard.search': 'వెతకండి',
      'dashboard.cart': 'కార్ట్',
      'dashboard.orders': 'ఆర్డర్‌లు',
      
      'common.language': 'భాష',
      'common.save': 'సేవ్ చేయండి',
      'common.cancel': 'రద్దు చేయండి',
      'common.delete': 'తొలగించు',
      'common.edit': 'సవరించు',
      'common.loading': 'లోడ్ చేస్తోంది...',
      'common.error': 'లోపం',
      'common.success': 'విజయం',
    },
    KN: {
      'login.title': 'NammaSocietyಗೆ ಲಾಗಿನ್ ಮಾಡಿ',
      'login.username_password': 'ಬಳಕೆದಾರ ಹೆಸರು ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್',
      'login.mobile_otp': 'ಮೊಬೈಲ್ ಮತ್ತು OTP',
      'login.username': 'ಬಳಕೆದಾರ ಹೆಸರು',
      'login.password': 'ಪಾಸ್‌ವರ್ಡ್',
      'login.captcha': 'ಕ್ಯಾಪ್ಚಾ',
      'login.login_button': 'ಲಾಗಿನ್',
      'login.register': 'ಖಾತೆ ಇಲ್ಲದೇ? ನೋಂದಣಿ ಮಾಡಿ',
      'login.forgot_password': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತುಬಿಟ್ಟಿರಿ?',
      'login.mobile_number': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP ಕಳುಹಿಸಿ',
      'login.verify_otp': 'OTP ಪರಿಶೀಲಿಸಿ',
      'login.error': 'ಲಾಗಿನ್ ವಿಫಲವಾಗಿದೆ',
      'login.success': 'ಲಾಗಿನ್ ಸಫಲವಾಗಿದೆ',
      
      'register.title': 'NammaSocietyಗೆ ನೋಂದಣಿ ಮಾಡಿ',
      'register.full_name': 'ಪೂರ್ಣ ಹೆಸರು',
      'register.email': 'ಇಮೇಲ್',
      'register.mobile': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'register.password': 'ಪಾಸ್‌ವರ್ಡ್',
      'register.confirm_password': 'ಪಾಸ್‌ವರ್ಡ್ ಖಚಿತಪಡಿಸಿ',
      'register.register_button': 'ನೋಂದಣಿ ಮಾಡಿ',
      'register.already_member': 'ಈಗಾಗಿ ಸದಸ್ಯ? ಲಾಗಿನ್ ಮಾಡಿ',
      
      'dashboard.marketplace': 'ಮಾರುಕಟ್ಟೆ',
      'dashboard.guest_approvals': 'ಅತಿಥಿ ಅನುಮೋದನೆಗಳು',
      'dashboard.profile': 'ಪ್ರೋಫೈಲ್',
      'dashboard.logout': 'ಲಾಗ್ ಔಟ್',
      'dashboard.welcome': 'ಸುಸ್ವಾಗತ',
      'dashboard.search': 'ಹುಡುಕಿ',
      'dashboard.cart': 'ಕಾರ್ಟ್',
      'dashboard.orders': 'ಆದೇಶಗಳು',
      
      'common.language': 'ಭಾಷೆ',
      'common.save': 'ಉಳಿಸಿ',
      'common.cancel': 'ರದ್ದುಮಾಡಿ',
      'common.delete': 'ಅಳಿಸಿ',
      'common.edit': 'ಸಂಪಾದಿಸಿ',
      'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      'common.error': 'ದೋಷ',
      'common.success': 'ಯಶಸ್ವಿ',
    },
    ML: {
      'login.title': 'NammaSocietyയിലേക്ക് ലോഗിൻ ചെയ്യുക',
      'login.username_password': 'ഉപയോഗിച്ചാരുപേര് കൂടാതെ പാസ്വേഡ്',
      'login.mobile_otp': 'മൊബൈൽ കൂടാതെ OTP',
      'login.username': 'ഉപയോഗിച്ചാരുപേര്',
      'login.password': 'പാസ്വേഡ്',
      'login.captcha': 'കാപ്റ്റായ',
      'login.login_button': 'ലോഗിൻ',
      'login.register': 'അക്കൗണ്ട് ഇല്ലെ? രജിസ്റ്റർ ചെയ്യുക',
      'login.forgot_password': 'പാസ്വേഡ് മറന്നുപോയിയോ?',
      'login.mobile_number': 'മൊബൈൽ നമ്പർ',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP അയയ്ക്കുക',
      'login.verify_otp': 'OTP പരിശോധിക്കുക',
      'login.error': 'ലോഗിൻ പരാജയപ്പെട്ടു',
      'login.success': 'ലോഗിൻ വിജയകരമായി',
      
      'register.title': 'NammaSocietyയിൽ രജിസ്റ്റർ ചെയ്യുക',
      'register.full_name': 'പൂർണ്ണ നാമം',
      'register.email': 'ഇമെയിൽ',
      'register.mobile': 'മൊബൈൽ നമ്പർ',
      'register.password': 'പാസ്വേഡ്',
      'register.confirm_password': 'പാസ്വേഡ് സ്ഥിരീകരിക്കുക',
      'register.register_button': 'രജിസ്റ്റർ ചെയ്യുക',
      'register.already_member': 'ഇതിനകം മെമ്പർ? ലോഗിൻ ചെയ്യുക',
      
      'dashboard.marketplace': 'മാർക്കറ്റ്പ്ലേസ്',
      'dashboard.guest_approvals': 'അതിഥി അനുമതികൾ',
      'dashboard.profile': 'പ്രൊഫിൽ',
      'dashboard.logout': 'ലോഗ് ഔട്ട്',
      'dashboard.welcome': 'സ്വാഗതം',
      'dashboard.search': 'തിരയുക',
      'dashboard.cart': 'കർട്ട്',
      'dashboard.orders': 'ഓർഡറുകൾ',
      
      'common.language': 'ഭാഷ',
      'common.save': 'സംരക്ഷിക്കുക',
      'common.cancel': 'റദ്ദാക്കുക',
      'common.delete': 'ഡിലീറ്റ് ചെയ്യുക',
      'common.edit': 'എഡിറ്റ് ചെയ്യുക',
      'common.loading': 'ലോഡ് ചെയ്യുന്നു...',
      'common.error': 'പിഴവ്',
      'common.success': 'വിജയം',
    },
    BN: {
      'login.title': 'NammaSocietyতে লগইন করুন',
      'login.username_password': 'ব্যবহারকারীর নাম এবং পাসওয়ার্ড',
      'login.mobile_otp': 'মোবাইল এবং OTP',
      'login.username': 'ব্যবহারকারীর নাম',
      'login.password': 'পাসওয়ার্ড',
      'login.captcha': 'ক্যাপচা',
      'login.login_button': 'লগইন',
      'login.register': 'অ্যাকাউন্ট নেই? নিবন্ধন করুন',
      'login.forgot_password': 'পাসওয়ার্ড ভুলে গেছেন?',
      'login.mobile_number': 'মোবাইল নম্বর',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP পাঠান',
      'login.verify_otp': 'OTP যাচাই করুন',
      'login.error': 'লগইন ব্যর্থ',
      'login.success': 'লগইন সফল',
      
      'register.title': 'NammaSocietyতে নিবন্ধন করুন',
      'register.full_name': 'সম্পূর্ণ নাম',
      'register.email': 'ইমেল',
      'register.mobile': 'মোবাইল নম্বর',
      'register.password': 'পাসওয়ার্ড',
      'register.confirm_password': 'পাসওয়ার্ড নিশ্চিত করুন',
      'register.register_button': 'নিবন্ধন করুন',
      'register.already_member': 'ইতিমধ্যে সদস্য? লগইন করুন',
      
      'dashboard.marketplace': 'বাজারপ্লেস',
      'dashboard.guest_approvals': 'অতিথি অনুমোদন',
      'dashboard.profile': 'প্রোফাইল',
      'dashboard.logout': 'লগ আউট',
      'dashboard.welcome': 'স্বাগতম',
      'dashboard.search': 'অনুসন্ধান',
      'dashboard.cart': 'কার্ট',
      'dashboard.orders': 'অর্ডার',
      
      'common.language': 'ভাষা',
      'common.save': 'সংরক্ষণ করুন',
      'common.cancel': 'বাতিল করুন',
      'common.delete': 'মুছুন',
      'common.edit': 'সম্পাদনা করুন',
      'common.loading': 'লোড হচ্ছে...',
      'common.error': 'ত্রুটি',
      'common.success': 'সফল',
    },
    MR: {
      'login.title': 'NammaSocietyमध्ये लॉगिन करा',
      'login.username_password': 'वापरकर्ता नाव आणि पासवर्ड',
      'login.mobile_otp': 'मोबाइल आणि OTP',
      'login.username': 'वापरकर्ता नाव',
      'login.password': 'पासवर्ड',
      'login.captcha': 'कॅप्चा',
      'login.login_button': 'लॉगिन',
      'login.register': 'खाते नाही? नोंदणी करा',
      'login.forgot_password': 'पासवर्ड विसरला?',
      'login.mobile_number': 'मोबाइल क्रमांक',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP पाठवा',
      'login.verify_otp': 'OTP सत्यापित करा',
      'login.error': 'लॉगिन अयोग्य',
      'login.success': 'लॉगिन यशस्वी',
      
      'register.title': 'NammaSocietyमध्ये नोंदणी करा',
      'register.full_name': 'पूर्ण नाव',
      'register.email': 'ईमेल',
      'register.mobile': 'मोबाइल क्रमांक',
      'register.password': 'पासवर्ड',
      'register.confirm_password': 'पासवर्ड पुष्टी करा',
      'register.register_button': 'नोंदणी करा',
      'register.already_member': 'आधीच सदस्य? लॉगिन करा',
      
      'dashboard.marketplace': 'मार्केटप्लेस',
      'dashboard.guest_approvals': 'अतिथी मंजूरी',
      'dashboard.profile': 'प्रोफाइल',
      'dashboard.logout': 'लॉग आउट',
      'dashboard.welcome': 'स्वागत आहे',
      'dashboard.search': 'शोध',
      'dashboard.cart': 'कार्ट',
      'dashboard.orders': 'ऑर्डर',
      
      'common.language': 'भाषा',
      'common.save': 'सेव करा',
      'common.cancel': 'रद्द करा',
      'common.delete': 'हटवा',
      'common.edit': 'संपादित करा',
      'common.loading': 'लोड होत आहे...',
      'common.error': 'त्रुटी',
      'common.success': 'यशस्वी',
    },
    GU: {
      'login.title': 'NammaSocietyમાં લૉગિન કરો',
      'login.username_password': 'વપરાશકર્તા નામ અને પાસવર્ડ',
      'login.mobile_otp': 'મોબાઈલ અને OTP',
      'login.username': 'વપરાશકર્તા નામ',
      'login.password': 'પાસવર્ડ',
      'login.captcha': 'કેપચા',
      'login.login_button': 'લૉગિન',
      'login.register': 'ખાતું નથી? નોંધણી કરો',
      'login.forgot_password': 'પાસવર્ડ ભૂલી ગયા?',
      'login.mobile_number': 'મોબાઈલ નંબર',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP મોકલો',
      'login.verify_otp': 'OTP ચકાસો',
      'login.error': 'લૉગિન વિફળ',
      'login.success': 'લૉગિન સફળ',
      
      'register.title': 'NammaSocietyમાં નોંધણી કરો',
      'register.full_name': 'પૂરું નામ',
      'register.email': 'ઈમેલ',
      'register.mobile': 'મોબાઈલ નંબર',
      'register.password': 'પાસવર્ડ',
      'register.confirm_password': 'પાસવર્ડ પુષ્ટિ કરો',
      'register.register_button': 'નોંધણી કરો',
      'register.already_member': 'પહેલેથી સભ્ય? લૉગિન કરો',
      
      'dashboard.marketplace': 'માર્કેટપ્લેસ',
      'dashboard.guest_approvals': 'અતિથિ માંજૂરીઓ',
      'dashboard.profile': 'પ્રોફાઈલ',
      'dashboard.logout': 'લૉગ આઉટ',
      'dashboard.welcome': 'સ્વાગત',
      'dashboard.search': 'શોધો',
      'dashboard.cart': 'કાર્ટ',
      'dashboard.orders': 'ઓર્ડર',
      
      'common.language': 'ભાષા',
      'common.save': 'સાચવો',
      'common.cancel': 'રદ્દ કરો',
      'common.delete': 'કાઢી નાખો',
      'common.edit': 'સંપાદિત કરો',
      'common.loading': 'લોડ થઈ રહ્યું છે...',
      'common.error': 'ભૂલ',
      'common.success': 'સફળ',
    },
    PA: {
      'login.title': 'NammaSocietyਵਿੱਚ ਲਾਗ ਇਨ ਕਰੋ',
      'login.username_password': 'ਵਰਤੋਂਕਾਰ ਨਾਮ ਅਤੇ ਪਾਸਵਰਡ',
      'login.mobile_otp': 'ਮੋਬਾਈਲ ਅਤੇ OTP',
      'login.username': 'ਵਰਤੋਂਕਾਰ ਨਾਮ',
      'login.password': 'ਪਾਸਵਰਡ',
      'login.captcha': 'ਕੈਪਚਾ',
      'login.login_button': 'ਲਾਗ ਇਨ',
      'login.register': 'ਖਾਤਾ ਨਹੀਂ? ਰਜਿਸਟਰ ਕਰੋ',
      'login.forgot_password': 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
      'login.mobile_number': 'ਮੋਬਾਈਲ ਨੰਬਰ',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP ਭੇਜੋ',
      'login.verify_otp': 'OTP ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      'login.error': 'ਲਾਗ ਇਨ ਅਸਫਲ',
      'login.success': 'ਲਾਗ ਇਨ ਸਫਲ',
      
      'register.title': 'NammaSocietyਵਿੱਚ ਰਜਿਸਟਰ ਕਰੋ',
      'register.full_name': 'ਪੂਰਾ ਨਾਮ',
      'register.email': 'ਈਮੇਲ',
      'register.mobile': 'ਮੋਬਾਈਲ ਨੰਬਰ',
      'register.password': 'ਪਾਸਵਰਡ',
      'register.confirm_password': 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      'register.register_button': 'ਰਜਿਸਟਰ ਕਰੋ',
      'register.already_member': 'ਪਹਿਲਾਂ ਹੀ ਮੈਂਬਰ? ਲਾਗ ਇਨ ਕਰੋ',
      
      'dashboard.marketplace': 'ਮਾਰਕੀਟਪਲੇਸ',
      'dashboard.guest_approvals': 'ਮਹਿमান ਮਨਜੂਰੀਆਂ',
      'dashboard.profile': 'ਪ੍ਰੋਫਾਈਲ',
      'dashboard.logout': 'ਲਾਗ ਆਊਟ',
      'dashboard.welcome': 'ਸਵਾਗਤ',
      'dashboard.search': 'ਖੋਜ',
      'dashboard.cart': 'ਕਾਰਟ',
      'dashboard.orders': 'ਆਰਡਰ',
      
      'common.language': 'ਭਾਸ਼ਾ',
      'common.save': 'ਸੇਵ ਕਰੋ',
      'common.cancel': 'ਰੱਦ ਕਰੋ',
      'common.delete': 'ਮਿਟਾਓ',
      'common.edit': 'ਸੰਪਾਦਿਤ ਕਰੋ',
      'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
      'common.error': 'ਗਲਤੀ',
      'common.success': 'ਸਫਲ',
    },
    OR: {
      'login.title': 'NammaSocietyରେ ଲଗଇନ କରନ୍ତୁ',
      'login.username_password': 'ବ୍ୟବହାରକାରୀ ନାମ ଏବଂ ଯୋଗାଶବ୍ଦ',
      'login.mobile_otp': 'ମୋବାଇଲ ଏବଂ OTP',
      'login.username': 'ବ୍ୟବହାରକାରୀ ନାମ',
      'login.password': 'ଯୋଗାଶବ୍ଦ',
      'login.captcha': 'କ୍ୟାପଚା',
      'login.login_button': 'ଲଗଇନ',
      'login.register': 'ଖାତା ନାହିଁ? ରେଜିସ୍ଟର କରନ୍ତୁ',
      'login.forgot_password': 'ଯୋଗାଶବ୍ଦ ଭୁଲିଗଛନ୍ତି?',
      'login.mobile_number': 'ମୋବାଇଲ ସଂଖ୍ୟା',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP ପଠାନ୍ତୁ',
      'login.verify_otp': 'OTP ଯାଞ୍ଚାଇ ନିନ୍ତୁ',
      'login.error': 'ଲଗଇନ ବିଫଳ',
      'login.success': 'ଲଗଇନ ସଫଳ',
      
      'register.title': 'NammaSocietyରେ ରେଜିସ୍ଟର କରନ୍ତୁ',
      'register.full_name': 'ପୂର୍ଣ୍ଣ ନାମ',
      'register.email': 'ଇମେଲ',
      'register.mobile': 'ମୋବାଇଲ ସଂଖ୍ୟା',
      'register.password': 'ଯୋଗାଶବ୍ଦ',
      'register.confirm_password': 'ଯୋଗାଶବ୍ଦ ନିଶ୍ଚିତ କରନ୍ତୁ',
      'register.register_button': 'ରେଜିସ୍ଟର କରନ୍ତୁ',
      'register.already_member': 'ଇତିପୂର୍ବରୁ ସଦସ୍ୟ? ଲଗଇନ କରନ୍ତୁ',
      
      'dashboard.marketplace': 'ମାର୍କେଟପ୍ଲେସ',
      'dashboard.guest_approvals': 'ଅତିଥି ଅନୁମୋଦନ',
      'dashboard.profile': 'ପ୍ରୋଫାଇଲ',
      'dashboard.logout': 'ଲଗଆଉଟ',
      'dashboard.welcome': 'ସ୍ୱାଗତମ',
      'dashboard.search': 'ଖୋଜନ୍ତୁ',
      'dashboard.cart': 'କାର୍ଟ',
      'dashboard.orders': 'ଅର୍ଡର',
      
      'common.language': 'ଭାଷା',
      'common.save': 'ସଂରକ୍ଷଣ କରନ୍ତୁ',
      'common.cancel': 'ରଦ୍ଦ କରନ୍ତୁ',
      'common.delete': 'ଡିଲିଟ କରନ୍ତୁ',
      'common.edit': 'ସଂପାଦନ କରନ୍ତୁ',
      'common.loading': 'ଲୋଡ ହେବାରେ ଅଛି...',
      'common.error': 'ତୃଟି',
      'common.success': 'ସଫଳ',
    },
    AS: {
      'login.title': 'NammaSocietyত প্রৱেশ কৰক',
      'login.username_password': 'ব্যৱহাৰকাৰীৰ নাম আৰু পাছৱৰ্ড',
      'login.mobile_otp': 'মোবাইল আৰু OTP',
      'login.username': 'ব্যৱহাৰকাৰীৰ নাম',
      'login.password': 'পাছৱৰ্ড',
      'login.captcha': 'কেপছা',
      'login.login_button': 'প্রৱেশ',
      'login.register': 'এটা একাউণ্ট নাই? নিবন্ধন কৰক',
      'login.forgot_password': 'পাছৱৰ্ড পাহৰি গল?',
      'login.mobile_number': 'মোবাইল নম্বৰ',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP পঠিয়াক',
      'login.verify_otp': 'OTP যাচাই কৰক',
      'login.error': 'প্রৱেশ ব্যর্থ',
      'login.success': 'প্রৱেশ সফল',
      
      'register.title': 'NammaSocietyত নিবন্ধন কৰক',
      'register.full_name': 'সম্পূৰ্ণ নাম',
      'register.email': 'ইমেইল',
      'register.mobile': 'মোবাইল নম্বৰ',
      'register.password': 'পাছৱৰ্ড',
      'register.confirm_password': 'পাছৱৰ্ড নিশ্চিত কৰক',
      'register.register_button': 'নিবন্ধন কৰক',
      'register.already_member': 'ইতিমধ্যে সদস্য? প্রৱেশ কৰক',
      
      'dashboard.marketplace': 'বজাৰ স্থান',
      'dashboard.guest_approvals': 'অতিথি অনুমোদন',
      'dashboard.profile': 'প্রোফাইল',
      'dashboard.logout': 'লগ আউট',
      'dashboard.welcome': 'স্বাগত',
      'dashboard.search': 'সন্ধান কৰক',
      'dashboard.cart': 'কাৰ্ট',
      'dashboard.orders': 'অৰ্ডাৰ',
      
      'common.language': 'ভাষা',
      'common.save': 'সংৰক্ষণ কৰক',
      'common.cancel': 'বাতিল কৰক',
      'common.delete': 'মুছি পেলাক',
      'common.edit': 'সম্পাদনা কৰক',
      'common.loading': 'লোড হৈ আছে...',
      'common.error': 'ত্রুটি',
      'common.success': 'সফল',
    },
  };

  constructor() { }

  private getInitialLanguage(): string {
    const saved = localStorage.getItem('amp_app_language');
    return saved || 'EN';
  }

  setLanguage(langCode: string): void {
    this.currentLanguage.next(langCode);
    localStorage.setItem('amp_app_language', langCode);
  }

  getCurrentLanguage(): string {
    return this.currentLanguage.value;
  }

  translate(key: string, defaultValue?: string): string {
    const lang = this.currentLanguage.value;
    const translation = this.translations[lang]?.[key];
    return translation || defaultValue || key;
  }

  getLanguages() {
    return [
      { code: 'EN', label: 'English' },
      { code: 'HI', label: 'हिन्दी' },
      { code: 'TA', label: 'தமிழ்' },
      { code: 'TE', label: 'తెలుగు' },
      { code: 'KN', label: 'ಕನ್ನಡ' },
      { code: 'ML', label: 'മലയാളം' },
      { code: 'BN', label: 'বাংলা' },
      { code: 'MR', label: 'मराठी' },
      { code: 'GU', label: 'ગુજરાતી' },
      { code: 'PA', label: 'ਪੰਜਾਬੀ' },
      { code: 'OR', label: 'ଓଡ଼ିଆ' },
      { code: 'AS', label: 'অসমীয়া' },
    ];
  }
}
