import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private currentLanguage = new BehaviorSubject<string>(this.getInitialLanguage());
  public currentLanguage$ = this.currentLanguage.asObservable();

  private translations: Translations = {
    EN: {
      'login.title': 'Login to NammaSociety',
      'login.username_password': 'Username & Password',
      'login.mobile_otp': 'Mobile & OTP',
      'login.username': 'Username',
      'login.password': 'Password',
      'login.captcha': 'Captcha',
      'login.login_button': 'Login',
      'login.register': "Don't have an account? Register",
      'login.forgot_password': 'Forgot Password?',
      'login.mobile_number': 'Mobile Number',
      'login.otp': 'OTP',
      'login.send_otp': 'Send OTP',
      'login.verify_otp': 'Verify OTP',
      'login.error': 'Login failed',
      'login.success': 'Login successful',
      'common.language': 'Language',
      'common.save': 'Save',
      'common.cancel': 'Cancel',
      'common.loading': 'Loading...',
    },
    HI: {
      'login.title': 'NammaSociety में लॉगिन करें',
      'login.username_password': 'यूजरनेम और पासवर्ड',
      'login.mobile_otp': 'मोबाइल और OTP',
      'login.username': 'यूजरनेम',
      'login.password': 'पासवर्ड',
      'login.captcha': 'कैप्चा',
      'login.login_button': 'लॉगिन',
      'login.register': 'खाता नहीं है? पंजीकरण करें',
      'login.forgot_password': 'पासवर्ड भूल गए?',
      'login.mobile_number': 'मोबाइल नंबर',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP भेजें',
      'login.verify_otp': 'OTP सत्यापित करें',
      'login.error': 'लॉगिन विफल',
      'login.success': 'लॉगिन सफल',
      'common.language': 'भाषा',
      'common.save': 'सहेजें',
      'common.cancel': 'रद्द करें',
      'common.loading': 'लोड हो रहा है...',
    },
    TA: {
      'login.title': 'NammaSociety இல் உள்நுழையவும்',
      'login.username_password': 'பயனர்பெயர் மற்றும் கடவுச்சொல்',
      'login.mobile_otp': 'மொபைல் மற்றும் OTP',
      'login.username': 'பயனர்பெயர்',
      'login.password': 'கடவுச்சொல்',
      'login.captcha': 'கேப்சா',
      'login.login_button': 'உள்நுழைக',
      'login.register': 'கணக்கு இல்லையா? பதிவு செய்க',
      'login.forgot_password': 'கடவுச்சொல் மறந்துவிட்டீர்களா?',
      'login.mobile_number': 'மொபைல் எண்',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP அனுப்பவும்',
      'login.verify_otp': 'OTP சரிபார்க்கவும்',
      'login.error': 'உள்நுழைவு தோல்வி',
      'login.success': 'உள்நுழைவு வெற்றிகரமாக',
      'common.language': 'மொழி',
      'common.save': 'சேமிக்கவும்',
      'common.cancel': 'ரத்து செய்க',
      'common.loading': 'சுமைப்பு நடைபெறுகிறது...',
    },
    TE: {
      'login.title': 'NammaSocietyకి లాగిన్ చేయండి',
      'login.username_password': 'వినియోగదారు పేరు మరియు పాస్‌వర్డ్',
      'login.mobile_otp': 'మొబైల్ మరియు OTP',
      'login.username': 'వినియోగదారు పేరు',
      'login.password': 'పాస్‌వర్డ్',
      'login.captcha': 'కాప్చా',
      'login.login_button': 'లాగిన్',
      'login.register': 'ఖాతా లేనా? నమోదు చేయండి',
      'login.forgot_password': 'పాస్‌వర్డ్ మర్చిపోయారా?',
      'login.mobile_number': 'మొబైల్ నంబర్',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP పంపండి',
      'login.verify_otp': 'OTPని ధృవీకరించండి',
      'login.error': 'లాగిన్ విఫలమైంది',
      'login.success': 'లాగిన్ విజయవంతమైంది',
      'common.language': 'భాష',
      'common.save': 'సేవ్ చేయండి',
      'common.cancel': 'రద్దు చేయండి',
      'common.loading': 'లోడ్ చేస్తోంది...',
    },
    KN: {
      'login.title': 'NammaSocietyಗೆ ಲಾಗಿನ್ ಮಾಡಿ',
      'login.username_password': 'ಬಳಕೆದಾರ ಹೆಸರು ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್',
      'login.mobile_otp': 'ಮೊಬೈಲ್ ಮತ್ತು OTP',
      'login.username': 'ಬಳಕೆದಾರ ಹೆಸರು',
      'login.password': 'ಪಾಸ್‌ವರ್ಡ್',
      'login.captcha': 'ಕ್ಯಾಪ್ಚಾ',
      'login.login_button': 'ಲಾಗಿನ್',
      'login.register': 'ಖಾತೆ ಇಲ್ಲದೇ? ನೋಂದಣಿ ಮಾಡಿ',
      'login.forgot_password': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತುಬಿಟ್ಟಿರಿ?',
      'login.mobile_number': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP ಕಳುಹಿಸಿ',
      'login.verify_otp': 'OTP ಪರಿಶೀಲಿಸಿ',
      'login.error': 'ಲಾಗಿನ್ ವಿಫಲವಾಗಿದೆ',
      'login.success': 'ಲಾಗಿನ್ ಸಫಲವಾಗಿದೆ',
      'common.language': 'ಭಾಷೆ',
      'common.save': 'ಉಳಿಸಿ',
      'common.cancel': 'ರದ್ದುಮಾಡಿ',
      'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    },
    ML: {
      'login.title': 'NammaSocietyയിലേക്ക് ലോഗിൻ ചെയ്യുക',
      'login.username_password': 'ഉപയോഗിച്ചാരുപേര് കൂടാതെ പാസ്വേഡ്',
      'login.mobile_otp': 'മൊബൈൽ കൂടാതെ OTP',
      'login.username': 'ഉപയോഗിച്ചാരുപേര്',
      'login.password': 'പാസ്വേഡ്',
      'login.captcha': 'കാപ്റ്റായ',
      'login.login_button': 'ലോഗിൻ',
      'login.register': 'അക്കൗണ്ട് ഇല്ലെ? രജിസ്റ്റർ ചെയ്യുക',
      'login.forgot_password': 'പാസ്വേഡ് മറന്നുപോയിയോ?',
      'login.mobile_number': 'മൊബൈൽ നമ്പർ',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP അയയ്ക്കുക',
      'login.verify_otp': 'OTP പരിശോധിക്കുക',
      'login.error': 'ലോഗിൻ പരാജയപ്പെട്ടു',
      'login.success': 'ലോഗിൻ വിജയകരമായി',
      'common.language': 'ഭാഷ',
      'common.save': 'സംരക്ഷിക്കുക',
      'common.cancel': 'റദ്ദാക്കുക',
      'common.loading': 'ലോഡ് ചെയ്യുന്നു...',
    },
    BN: {
      'login.title': 'NammaSocietyতে লগইন করুন',
      'login.username_password': 'ব্যবহারকারীর নাম এবং পাসওয়ার্ড',
      'login.mobile_otp': 'মোবাইল এবং OTP',
      'login.username': 'ব্যবহারকারীর নাম',
      'login.password': 'পাসওয়ার্ড',
      'login.captcha': 'ক্যাপচা',
      'login.login_button': 'লগইন',
      'login.register': 'অ্যাকাউন্ট নেই? নিবন্ধন করুন',
      'login.forgot_password': 'পাসওয়ার্ড ভুলে গেছেন?',
      'login.mobile_number': 'মোবাইল নম্বর',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP পাঠান',
      'login.verify_otp': 'OTP যাচাই করুন',
      'login.error': 'লগইন ব্যর্থ',
      'login.success': 'লগইন সফল',
      'common.language': 'ভাষা',
      'common.save': 'সংরক্ষণ করুন',
      'common.cancel': 'বাতিল করুন',
      'common.loading': 'লোড হচ্ছে...',
    },
    MR: {
      'login.title': 'NammaSocietyमध्ये लॉगिन करा',
      'login.username_password': 'वापरकर्ता नाव आणि पासवर्ड',
      'login.mobile_otp': 'मोबाइल आणि OTP',
      'login.username': 'वापरकर्ता नाव',
      'login.password': 'पासवर्ड',
      'login.captcha': 'कॅप्चा',
      'login.login_button': 'लॉगिन',
      'login.register': 'खाते नाही? नोंदणी करा',
      'login.forgot_password': 'पासवर्ड विसरला?',
      'login.mobile_number': 'मोबाइल क्रमांक',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP पाठवा',
      'login.verify_otp': 'OTP सत्यापित करा',
      'login.error': 'लॉगिन अयोग्य',
      'login.success': 'लॉगिन यशस्वी',
      'common.language': 'भाषा',
      'common.save': 'सेव करा',
      'common.cancel': 'रद्द करा',
      'common.loading': 'लोड होत आहे...',
    },
    GU: {
      'login.title': 'NammaSocietyમાં લૉગિન કરો',
      'login.username_password': 'વપરાશકર્તા નામ અને પાસવર્ડ',
      'login.mobile_otp': 'મોબાઈલ અને OTP',
      'login.username': 'વપરાશકર્તા નામ',
      'login.password': 'પાસવર્ડ',
      'login.captcha': 'કેપચા',
      'login.login_button': 'લૉગિન',
      'login.register': 'ખાતું નથી? નોંધણી કરો',
      'login.forgot_password': 'પાસવર્ડ ભૂલી ગયા?',
      'login.mobile_number': 'મોબાઈલ નંબર',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP મોકલો',
      'login.verify_otp': 'OTP ચકાસો',
      'login.error': 'લૉગિન વિફળ',
      'login.success': 'લૉગિન સફળ',
      'common.language': 'ભાષા',
      'common.save': 'સાચવો',
      'common.cancel': 'રદ્દ કરો',
      'common.loading': 'લોડ થઈ રહ્યું છે...',
    },
    PA: {
      'login.title': 'NammaSocietyਵਿੱਚ ਲਾਗ ਇਨ ਕਰੋ',
      'login.username_password': 'ਵਰਤੋਂਕਾਰ ਨਾਮ ਅਤੇ ਪਾਸਵਰਡ',
      'login.mobile_otp': 'ਮੋਬਾਈਲ ਅਤੇ OTP',
      'login.username': 'ਵਰਤੋਂਕਾਰ ਨਾਮ',
      'login.password': 'ਪਾਸਵਰਡ',
      'login.captcha': 'ਕੈਪਚਾ',
      'login.login_button': 'ਲਾਗ ਇਨ',
      'login.register': 'ਖਾਤਾ ਨਹੀਂ? ਰਜਿਸਟਰ ਕਰੋ',
      'login.forgot_password': 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
      'login.mobile_number': 'ਮੋਬਾਈਲ ਨੰਬਰ',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP ਭੇਜੋ',
      'login.verify_otp': 'OTP ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      'login.error': 'ਲਾਗ ਇਨ ਅਸਫਲ',
      'login.success': 'ਲਾਗ ਇਨ ਸਫਲ',
      'common.language': 'ਭਾਸ਼ਾ',
      'common.save': 'ਸੇਵ ਕਰੋ',
      'common.cancel': 'ਰੱਦ ਕਰੋ',
      'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    },
    OR: {
      'login.title': 'NammaSocietyରେ ଲଗଇନ କରନ୍ତୁ',
      'login.username_password': 'ବ୍ୟବହାରକାରୀ ନାମ ଏବଂ ଯୋଗାଶବ୍ଦ',
      'login.mobile_otp': 'ମୋବାଇଲ ଏବଂ OTP',
      'login.username': 'ବ୍ୟବହାରକାରୀ ନାମ',
      'login.password': 'ଯୋଗାଶବ୍ଦ',
      'login.captcha': 'କ୍ୟାପଚା',
      'login.login_button': 'ଲଗଇନ',
      'login.register': 'ଖାତା ନାହିଁ? ରେଜିସ୍ଟର କରନ୍ତୁ',
      'login.forgot_password': 'ଯୋଗାଶବ୍ଦ ଭୁଲିଗଛନ୍ତି?',
      'login.mobile_number': 'ମୋବାଇଲ ସଂଖ୍ୟା',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP ପଠାନ୍ତୁ',
      'login.verify_otp': 'OTP ଯାଞ୍ଚାଇ ନିନ୍ତୁ',
      'login.error': 'ଲଗଇନ ବିଫଳ',
      'login.success': 'ଲଗଇନ ସଫଳ',
      'common.language': 'ଭାଷା',
      'common.save': 'ସଂରକ୍ଷଣ କରନ୍ତୁ',
      'common.cancel': 'ରଦ୍ଦ କରନ୍ତୁ',
      'common.loading': 'ଲୋଡ ହେବାରେ ଅଛି...',
    },
    AS: {
      'login.title': 'NammaSocietyত প्रৱेश कৰक',
      'login.username_password': 'ব্যৱহাৰকাৰীৰ নাম আৰু পাছৱৰ্ড',
      'login.mobile_otp': 'মোবাইল আৰু OTP',
      'login.username': 'ব্যৱহাৰকাৰীৰ নাম',
      'login.password': 'পাছৱৰ্ড',
      'login.captcha': 'কেপছা',
      'login.login_button': 'प्রৱेश',
      'login.register': 'এটা একাউণ্ট নাই? নিবন্ধন কৰক',
      'login.forgot_password': 'পাছৱৰ্ড পাহৰি গল?',
      'login.mobile_number': 'মোবাইল নম्बৰ',
      'login.otp': 'OTP',
      'login.send_otp': 'OTP पठিয়াक',
      'login.verify_otp': 'OTP যاচাই कৰك',
      'login.error': 'प्रৱেश ব्यर्थ',
      'login.success': 'प्रৱेश सফल',
      'common.language': 'ভাষা',
      'common.save': 'সংৰক्ষণ कৰক',
      'common.cancel': 'বাতिल кৰক',
      'common.loading': 'लोड हैруआहे...',
    },
  };

  constructor() { }

  private getInitialLanguage(): string {
    const saved = localStorage.getItem('amp_app_language');
    return saved || 'EN';
  }

  setLanguage(langCode: string): void {
    this.currentLanguage.next(langCode);
    localStorage.setItem('amp_app_language', langCode);
  }

  getCurrentLanguage(): string {
    return this.currentLanguage.value;
  }

  translate(key: string, defaultValue?: string): string {
    const lang = this.currentLanguage.value;
    const translation = this.translations[lang]?.[key];
    return translation || defaultValue || key;
  }

  getLanguages() {
    return [
      { code: 'EN', label: 'English' },
      { code: 'HI', label: 'हिन्दी' },
      { code: 'TA', label: 'தமிழ்' },
      { code: 'TE', label: 'తెలుగు' },
      { code: 'KN', label: 'ಕನ್ನಡ' },
      { code: 'ML', label: 'മലയാളം' },
      { code: 'BN', label: 'বাংলা' },
      { code: 'MR', label: 'मराठी' },
      { code: 'GU', label: 'ગુજરાતી' },
      { code: 'PA', label: 'ਪੰਜਾਬੀ' },
      { code: 'OR', label: 'ଓଡ଼ିଆ' },
      { code: 'AS', label: 'অসমীয়া' },
    ];
  }
}
